[package]
name = "rsomics-bam"
version = "0.7.0"
description = "Coherent SAM, BAM, and CRAM inspection and transformation workflows"
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"
repository = "https://github.com/omics-rust/rsomics-bam"
homepage = "https://github.com/omics-rust/rsomics-bam"
documentation = "https://docs.rs/rsomics-bam"
readme = "README.md"
authors = ["Zane Leong <efd@live.com>"]
categories = ["science", "command-line-utilities"]
keywords = ["bam", "cram", "sam", "samtools", "bioinformatics"]

[lib]
name = "rsomics_bam"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "rsomics-bam"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
itoa = "1"
noodles = { version = "0.110", features = ["bam", "bgzf", "core", "cram", "csi", "fasta", "sam"] }
noodles-bgzf = { version = "0.47", features = ["libdeflate"] }
noodles-util = { version = "0.79", features = ["alignment"] }
rsomics-common = "0.12"
rsomics-bamio = "0.8.4"
rsomics-help = "0.4"
rsomics-pileup = "0.8"
rayon = "1"
rust-htslib = { version = "1.0.1", default-features = false, features = ["bzip2", "lzma", "libdeflate"] }
same-file = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
